<?php
return array (
  '2017_01_09_05_04_03' => 
  array (
    'date' => '2017_01_09_05_04_03',
    'current' => 
    array (
      1 => 'Amazon\\PayWithAmazon',
      3 => 'CDev\\AuthorizeNet',
      4 => 'CDev\\Bestsellers',
      5 => 'CDev\\ContactUs',
      6 => 'CDev\\Coupons',
      8 => 'CDev\\FeaturedProducts',
      9 => 'CDev\\FedEx',
      11 => 'CDev\\GoogleAnalytics',
      12 => 'CDev\\GoSocial',
      13 => 'CDev\\Moneybookers',
      14 => 'CDev\\Paypal',
      16 => 'CDev\\ProductAdvisor',
      17 => 'CDev\\Quantum',
      18 => 'CDev\\Sale',
      19 => 'CDev\\SalesTax',
      20 => 'CDev\\SimpleCMS',
      21 => 'CDev\\SocialLogin',
      22 => 'CDev\\TwoCheckout',
      23 => 'CDev\\UserPermissions',
      24 => 'CDev\\USPS',
      25 => 'CDev\\VolumeDiscounts',
      27 => 'CDev\\XMLSitemap',
      28 => 'CDev\\XPaymentsConnector',
      29 => 'QSL\\CloudSearch',
      30 => 'QSL\\FlyoutCategoriesMenu',
      33 => 'XC\\AuctionInc',
      34 => 'XC\\BulkEditing',
      35 => 'XC\\CanadaPost',
      37 => 'XC\\CrispWhiteSkin',
      39 => 'XC\\EPDQ',
      41 => 'XC\\FastLaneCheckout',
      42 => 'XC\\FreeShipping',
      43 => 'XC\\FroalaEditor',
      45 => 'XC\\IdealPayments',
      46 => 'XC\\MailChimp',
      48 => 'XC\\News',
      49 => 'XC\\NewsletterSubscriptions',
      55 => 'XC\\Reviews',
      56 => 'XC\\SagePay',
      58 => 'XC\\Stripe',
      59 => 'XC\\ThemeTweaker',
      60 => 'XC\\UpdateInventory',
      61 => 'XC\\UPS',
      62 => 'XC\\Upselling',
    ),
    'enabled' => 
    array (
    ),
    'disabled' => 
    array (
    ),
    'deleted' => 
    array (
    ),
    'installed' => 
    array (
      0 => 'XC\\MultiVendor',
    ),
  ),
  '2017_01_09_05_18_58' => 
  array (
    'date' => '2017_01_09_05_18_58',
    'current' => 
    array (
      1 => 'Amazon\\PayWithAmazon',
      3 => 'CDev\\AuthorizeNet',
      4 => 'CDev\\Bestsellers',
      5 => 'CDev\\ContactUs',
      6 => 'CDev\\Coupons',
      8 => 'CDev\\FeaturedProducts',
      9 => 'CDev\\FedEx',
      11 => 'CDev\\GoogleAnalytics',
      12 => 'CDev\\GoSocial',
      13 => 'CDev\\Moneybookers',
      14 => 'CDev\\Paypal',
      16 => 'CDev\\ProductAdvisor',
      17 => 'CDev\\Quantum',
      18 => 'CDev\\Sale',
      19 => 'CDev\\SalesTax',
      20 => 'CDev\\SimpleCMS',
      21 => 'CDev\\SocialLogin',
      22 => 'CDev\\TwoCheckout',
      23 => 'CDev\\UserPermissions',
      24 => 'CDev\\USPS',
      25 => 'CDev\\VolumeDiscounts',
      27 => 'CDev\\XMLSitemap',
      28 => 'CDev\\XPaymentsConnector',
      29 => 'QSL\\CloudSearch',
      30 => 'QSL\\FlyoutCategoriesMenu',
      33 => 'XC\\AuctionInc',
      34 => 'XC\\BulkEditing',
      35 => 'XC\\CanadaPost',
      37 => 'XC\\CrispWhiteSkin',
      39 => 'XC\\EPDQ',
      41 => 'XC\\FastLaneCheckout',
      42 => 'XC\\FreeShipping',
      43 => 'XC\\FroalaEditor',
      45 => 'XC\\IdealPayments',
      46 => 'XC\\MailChimp',
      48 => 'XC\\News',
      49 => 'XC\\NewsletterSubscriptions',
      55 => 'XC\\Reviews',
      56 => 'XC\\SagePay',
      58 => 'XC\\Stripe',
      59 => 'XC\\ThemeTweaker',
      60 => 'XC\\UpdateInventory',
      61 => 'XC\\UPS',
      62 => 'XC\\Upselling',
      221 => 'XC\\MultiVendor',
    ),
    'enabled' => 
    array (
    ),
    'disabled' => 
    array (
    ),
    'deleted' => 
    array (
    ),
    'installed' => 
    array (
      0 => 'Shofi\\AdvanceRegistration',
    ),
  ),
  '2017_01_09_05_21_26' => 
  array (
    'date' => '2017_01_09_05_21_26',
    'current' => 
    array (
      1 => 'Amazon\\PayWithAmazon',
      3 => 'CDev\\AuthorizeNet',
      4 => 'CDev\\Bestsellers',
      5 => 'CDev\\ContactUs',
      6 => 'CDev\\Coupons',
      8 => 'CDev\\FeaturedProducts',
      9 => 'CDev\\FedEx',
      11 => 'CDev\\GoogleAnalytics',
      12 => 'CDev\\GoSocial',
      13 => 'CDev\\Moneybookers',
      14 => 'CDev\\Paypal',
      16 => 'CDev\\ProductAdvisor',
      17 => 'CDev\\Quantum',
      18 => 'CDev\\Sale',
      19 => 'CDev\\SalesTax',
      20 => 'CDev\\SimpleCMS',
      21 => 'CDev\\SocialLogin',
      22 => 'CDev\\TwoCheckout',
      23 => 'CDev\\UserPermissions',
      24 => 'CDev\\USPS',
      25 => 'CDev\\VolumeDiscounts',
      27 => 'CDev\\XMLSitemap',
      28 => 'CDev\\XPaymentsConnector',
      29 => 'QSL\\CloudSearch',
      30 => 'QSL\\FlyoutCategoriesMenu',
      33 => 'XC\\AuctionInc',
      34 => 'XC\\BulkEditing',
      35 => 'XC\\CanadaPost',
      37 => 'XC\\CrispWhiteSkin',
      39 => 'XC\\EPDQ',
      41 => 'XC\\FastLaneCheckout',
      42 => 'XC\\FreeShipping',
      43 => 'XC\\FroalaEditor',
      45 => 'XC\\IdealPayments',
      46 => 'XC\\MailChimp',
      48 => 'XC\\News',
      49 => 'XC\\NewsletterSubscriptions',
      55 => 'XC\\Reviews',
      56 => 'XC\\SagePay',
      58 => 'XC\\Stripe',
      59 => 'XC\\ThemeTweaker',
      60 => 'XC\\UpdateInventory',
      61 => 'XC\\UPS',
      62 => 'XC\\Upselling',
      221 => 'XC\\MultiVendor',
      456 => 'Shofi\\AdvanceRegistration',
    ),
    'enabled' => 
    array (
    ),
    'disabled' => 
    array (
      456 => 'Shofi\\AdvanceRegistration',
    ),
    'deleted' => 
    array (
    ),
    'installed' => 
    array (
    ),
  ),
  '2017_01_09_05_23_42' => 
  array (
    'date' => '2017_01_09_05_23_42',
    'current' => 
    array (
      1 => 'Amazon\\PayWithAmazon',
      3 => 'CDev\\AuthorizeNet',
      4 => 'CDev\\Bestsellers',
      5 => 'CDev\\ContactUs',
      6 => 'CDev\\Coupons',
      8 => 'CDev\\FeaturedProducts',
      9 => 'CDev\\FedEx',
      11 => 'CDev\\GoogleAnalytics',
      12 => 'CDev\\GoSocial',
      13 => 'CDev\\Moneybookers',
      14 => 'CDev\\Paypal',
      16 => 'CDev\\ProductAdvisor',
      17 => 'CDev\\Quantum',
      18 => 'CDev\\Sale',
      19 => 'CDev\\SalesTax',
      20 => 'CDev\\SimpleCMS',
      21 => 'CDev\\SocialLogin',
      22 => 'CDev\\TwoCheckout',
      23 => 'CDev\\UserPermissions',
      24 => 'CDev\\USPS',
      25 => 'CDev\\VolumeDiscounts',
      27 => 'CDev\\XMLSitemap',
      28 => 'CDev\\XPaymentsConnector',
      29 => 'QSL\\CloudSearch',
      30 => 'QSL\\FlyoutCategoriesMenu',
      33 => 'XC\\AuctionInc',
      34 => 'XC\\BulkEditing',
      35 => 'XC\\CanadaPost',
      37 => 'XC\\CrispWhiteSkin',
      39 => 'XC\\EPDQ',
      41 => 'XC\\FastLaneCheckout',
      42 => 'XC\\FreeShipping',
      43 => 'XC\\FroalaEditor',
      45 => 'XC\\IdealPayments',
      46 => 'XC\\MailChimp',
      48 => 'XC\\News',
      49 => 'XC\\NewsletterSubscriptions',
      55 => 'XC\\Reviews',
      56 => 'XC\\SagePay',
      58 => 'XC\\Stripe',
      59 => 'XC\\ThemeTweaker',
      60 => 'XC\\UpdateInventory',
      61 => 'XC\\UPS',
      62 => 'XC\\Upselling',
      221 => 'XC\\MultiVendor',
    ),
    'enabled' => 
    array (
    ),
    'disabled' => 
    array (
    ),
    'deleted' => 
    array (
    ),
    'installed' => 
    array (
      0 => 'Shofi\\ToolListing',
    ),
  ),
  '2017_01_09_05_26_21' => 
  array (
    'date' => '2017_01_09_05_26_21',
    'current' => 
    array (
      1 => 'Amazon\\PayWithAmazon',
      3 => 'CDev\\AuthorizeNet',
      4 => 'CDev\\Bestsellers',
      5 => 'CDev\\ContactUs',
      6 => 'CDev\\Coupons',
      8 => 'CDev\\FeaturedProducts',
      9 => 'CDev\\FedEx',
      11 => 'CDev\\GoogleAnalytics',
      12 => 'CDev\\GoSocial',
      13 => 'CDev\\Moneybookers',
      14 => 'CDev\\Paypal',
      16 => 'CDev\\ProductAdvisor',
      17 => 'CDev\\Quantum',
      18 => 'CDev\\Sale',
      19 => 'CDev\\SalesTax',
      20 => 'CDev\\SimpleCMS',
      21 => 'CDev\\SocialLogin',
      22 => 'CDev\\TwoCheckout',
      23 => 'CDev\\UserPermissions',
      24 => 'CDev\\USPS',
      25 => 'CDev\\VolumeDiscounts',
      27 => 'CDev\\XMLSitemap',
      28 => 'CDev\\XPaymentsConnector',
      29 => 'QSL\\CloudSearch',
      30 => 'QSL\\FlyoutCategoriesMenu',
      33 => 'XC\\AuctionInc',
      34 => 'XC\\BulkEditing',
      35 => 'XC\\CanadaPost',
      37 => 'XC\\CrispWhiteSkin',
      39 => 'XC\\EPDQ',
      41 => 'XC\\FastLaneCheckout',
      42 => 'XC\\FreeShipping',
      43 => 'XC\\FroalaEditor',
      45 => 'XC\\IdealPayments',
      46 => 'XC\\MailChimp',
      48 => 'XC\\News',
      49 => 'XC\\NewsletterSubscriptions',
      55 => 'XC\\Reviews',
      56 => 'XC\\SagePay',
      58 => 'XC\\Stripe',
      59 => 'XC\\ThemeTweaker',
      60 => 'XC\\UpdateInventory',
      61 => 'XC\\UPS',
      62 => 'XC\\Upselling',
      221 => 'XC\\MultiVendor',
      457 => 'Shofi\\ToolListing',
    ),
    'enabled' => 
    array (
      456 => 'Shofi\\AdvanceRegistration',
    ),
    'disabled' => 
    array (
    ),
    'deleted' => 
    array (
    ),
    'installed' => 
    array (
    ),
  ),
  '2017_01_09_23_26_02' => 
  array (
    'date' => '2017_01_09_23_26_02',
    'current' => 
    array (
      1 => 'Amazon\\PayWithAmazon',
      3 => 'CDev\\AuthorizeNet',
      4 => 'CDev\\Bestsellers',
      5 => 'CDev\\ContactUs',
      6 => 'CDev\\Coupons',
      8 => 'CDev\\FeaturedProducts',
      9 => 'CDev\\FedEx',
      11 => 'CDev\\GoogleAnalytics',
      12 => 'CDev\\GoSocial',
      13 => 'CDev\\Moneybookers',
      14 => 'CDev\\Paypal',
      16 => 'CDev\\ProductAdvisor',
      17 => 'CDev\\Quantum',
      18 => 'CDev\\Sale',
      19 => 'CDev\\SalesTax',
      20 => 'CDev\\SimpleCMS',
      21 => 'CDev\\SocialLogin',
      22 => 'CDev\\TwoCheckout',
      23 => 'CDev\\UserPermissions',
      24 => 'CDev\\USPS',
      25 => 'CDev\\VolumeDiscounts',
      27 => 'CDev\\XMLSitemap',
      28 => 'CDev\\XPaymentsConnector',
      29 => 'QSL\\CloudSearch',
      30 => 'QSL\\FlyoutCategoriesMenu',
      35 => 'XC\\AuctionInc',
      36 => 'XC\\BulkEditing',
      37 => 'XC\\CanadaPost',
      39 => 'XC\\CrispWhiteSkin',
      41 => 'XC\\EPDQ',
      43 => 'XC\\FastLaneCheckout',
      44 => 'XC\\FreeShipping',
      45 => 'XC\\FroalaEditor',
      47 => 'XC\\IdealPayments',
      48 => 'XC\\MailChimp',
      51 => 'XC\\News',
      52 => 'XC\\NewsletterSubscriptions',
      58 => 'XC\\Reviews',
      59 => 'XC\\SagePay',
      61 => 'XC\\Stripe',
      62 => 'XC\\ThemeTweaker',
      63 => 'XC\\UpdateInventory',
      64 => 'XC\\UPS',
      65 => 'XC\\Upselling',
    ),
    'enabled' => 
    array (
      50 => 'XC\\MultiVendor',
    ),
    'disabled' => 
    array (
    ),
    'deleted' => 
    array (
    ),
    'installed' => 
    array (
    ),
  ),
  '2017_01_09_23_37_54' => 
  array (
    'date' => '2017_01_09_23_37_54',
    'current' => 
    array (
      1 => 'Amazon\\PayWithAmazon',
      3 => 'CDev\\AuthorizeNet',
      4 => 'CDev\\Bestsellers',
      5 => 'CDev\\ContactUs',
      6 => 'CDev\\Coupons',
      8 => 'CDev\\FeaturedProducts',
      9 => 'CDev\\FedEx',
      11 => 'CDev\\GoogleAnalytics',
      12 => 'CDev\\GoSocial',
      13 => 'CDev\\Moneybookers',
      14 => 'CDev\\Paypal',
      16 => 'CDev\\ProductAdvisor',
      17 => 'CDev\\Quantum',
      18 => 'CDev\\Sale',
      19 => 'CDev\\SalesTax',
      20 => 'CDev\\SimpleCMS',
      21 => 'CDev\\SocialLogin',
      22 => 'CDev\\TwoCheckout',
      23 => 'CDev\\UserPermissions',
      24 => 'CDev\\USPS',
      25 => 'CDev\\VolumeDiscounts',
      27 => 'CDev\\XMLSitemap',
      28 => 'CDev\\XPaymentsConnector',
      29 => 'QSL\\CloudSearch',
      30 => 'QSL\\FlyoutCategoriesMenu',
      35 => 'XC\\AuctionInc',
      36 => 'XC\\BulkEditing',
      37 => 'XC\\CanadaPost',
      39 => 'XC\\CrispWhiteSkin',
      41 => 'XC\\EPDQ',
      43 => 'XC\\FastLaneCheckout',
      44 => 'XC\\FreeShipping',
      45 => 'XC\\FroalaEditor',
      47 => 'XC\\IdealPayments',
      48 => 'XC\\MailChimp',
      50 => 'XC\\MultiVendor',
      51 => 'XC\\News',
      52 => 'XC\\NewsletterSubscriptions',
      58 => 'XC\\Reviews',
      59 => 'XC\\SagePay',
      61 => 'XC\\Stripe',
      62 => 'XC\\ThemeTweaker',
      63 => 'XC\\UpdateInventory',
      64 => 'XC\\UPS',
      65 => 'XC\\Upselling',
    ),
    'enabled' => 
    array (
      33 => 'Shofi\\ToolListing',
    ),
    'disabled' => 
    array (
    ),
    'deleted' => 
    array (
    ),
    'installed' => 
    array (
    ),
  ),
  '2017_01_09_23_43_16' => 
  array (
    'date' => '2017_01_09_23_43_16',
    'current' => 
    array (
      1 => 'Amazon\\PayWithAmazon',
      3 => 'CDev\\AuthorizeNet',
      4 => 'CDev\\Bestsellers',
      5 => 'CDev\\ContactUs',
      6 => 'CDev\\Coupons',
      8 => 'CDev\\FeaturedProducts',
      9 => 'CDev\\FedEx',
      11 => 'CDev\\GoogleAnalytics',
      12 => 'CDev\\GoSocial',
      13 => 'CDev\\Moneybookers',
      14 => 'CDev\\Paypal',
      16 => 'CDev\\ProductAdvisor',
      17 => 'CDev\\Quantum',
      18 => 'CDev\\Sale',
      19 => 'CDev\\SalesTax',
      20 => 'CDev\\SimpleCMS',
      21 => 'CDev\\SocialLogin',
      22 => 'CDev\\TwoCheckout',
      23 => 'CDev\\UserPermissions',
      24 => 'CDev\\USPS',
      25 => 'CDev\\VolumeDiscounts',
      27 => 'CDev\\XMLSitemap',
      28 => 'CDev\\XPaymentsConnector',
      29 => 'QSL\\CloudSearch',
      30 => 'QSL\\FlyoutCategoriesMenu',
      33 => 'Shofi\\ToolListing',
      35 => 'XC\\AuctionInc',
      36 => 'XC\\BulkEditing',
      37 => 'XC\\CanadaPost',
      39 => 'XC\\CrispWhiteSkin',
      41 => 'XC\\EPDQ',
      43 => 'XC\\FastLaneCheckout',
      44 => 'XC\\FreeShipping',
      45 => 'XC\\FroalaEditor',
      47 => 'XC\\IdealPayments',
      48 => 'XC\\MailChimp',
      50 => 'XC\\MultiVendor',
      51 => 'XC\\News',
      52 => 'XC\\NewsletterSubscriptions',
      58 => 'XC\\Reviews',
      59 => 'XC\\SagePay',
      61 => 'XC\\Stripe',
      62 => 'XC\\ThemeTweaker',
      63 => 'XC\\UpdateInventory',
      64 => 'XC\\UPS',
      65 => 'XC\\Upselling',
    ),
    'enabled' => 
    array (
    ),
    'disabled' => 
    array (
    ),
    'deleted' => 
    array (
    ),
    'installed' => 
    array (
      0 => 'Shofi\\AdvanceRegistration',
    ),
  ),
  '2017_01_09_23_45_31' => 
  array (
    'date' => '2017_01_09_23_45_31',
    'current' => 
    array (
      1 => 'Amazon\\PayWithAmazon',
      3 => 'CDev\\AuthorizeNet',
      4 => 'CDev\\Bestsellers',
      5 => 'CDev\\ContactUs',
      6 => 'CDev\\Coupons',
      8 => 'CDev\\FeaturedProducts',
      9 => 'CDev\\FedEx',
      11 => 'CDev\\GoogleAnalytics',
      12 => 'CDev\\GoSocial',
      13 => 'CDev\\Moneybookers',
      14 => 'CDev\\Paypal',
      16 => 'CDev\\ProductAdvisor',
      17 => 'CDev\\Quantum',
      18 => 'CDev\\Sale',
      19 => 'CDev\\SalesTax',
      20 => 'CDev\\SimpleCMS',
      21 => 'CDev\\SocialLogin',
      22 => 'CDev\\TwoCheckout',
      23 => 'CDev\\UserPermissions',
      24 => 'CDev\\USPS',
      25 => 'CDev\\VolumeDiscounts',
      27 => 'CDev\\XMLSitemap',
      28 => 'CDev\\XPaymentsConnector',
      29 => 'QSL\\CloudSearch',
      30 => 'QSL\\FlyoutCategoriesMenu',
      33 => 'Shofi\\ToolListing',
      35 => 'XC\\AuctionInc',
      36 => 'XC\\BulkEditing',
      37 => 'XC\\CanadaPost',
      39 => 'XC\\CrispWhiteSkin',
      41 => 'XC\\EPDQ',
      43 => 'XC\\FastLaneCheckout',
      44 => 'XC\\FreeShipping',
      45 => 'XC\\FroalaEditor',
      47 => 'XC\\IdealPayments',
      48 => 'XC\\MailChimp',
      50 => 'XC\\MultiVendor',
      51 => 'XC\\News',
      52 => 'XC\\NewsletterSubscriptions',
      58 => 'XC\\Reviews',
      59 => 'XC\\SagePay',
      61 => 'XC\\Stripe',
      62 => 'XC\\ThemeTweaker',
      63 => 'XC\\UpdateInventory',
      64 => 'XC\\UPS',
      65 => 'XC\\Upselling',
    ),
    'enabled' => 
    array (
      32 => 'Shofi\\AdvanceRegistration',
    ),
    'disabled' => 
    array (
    ),
    'deleted' => 
    array (
    ),
    'installed' => 
    array (
    ),
  ),
);